## Configuration file for Jekyll & Schrift template

#
# Jekyll configuration
#

# Global
safe: false
url: https://snowdj.github.io/prose
source:      https://snowdj.github.io/prose
destination: https://snowdj.github.io/prose/_site
plugins:     https://snowdj.github.io/prose/_plugins

# Server
port: 4000

# Build options
future:      true
lsi:         false
highlighter: rouge
markdown:    kramdown
permalink:   date
auto_ids:    true

#
# Schrift template configuration
#

# Enter below your name or pseudo & a short description
#    | These don't appear on the website. They are used to set the <META>s
author: Snowdj
description: A clean and minimalist Jekyll template. Designed for prose.
title: Writing template  # Appears in the window title of the browser. Stands alone on the homepage, sits beside the post title on post pages.

# Enter below the headtitle of your weblog/website
#    | It appears on the main navigation bar. You use <span></span> to nicely fade out some part of it
maintitle: Evergreen <span> for life</span>

# Enter below a short description that will sit next to your head title.
#    | {optional}
#maindesc: <a href=https://github.com/Schoewilliam/Schrift><span class=oi data-glyph=fork></span> Fork me</a>

# Enter below the items of your main menu
#    | Keep it a small amount. It is designed for a small menu.
menus:
- text: Archive
  url: /archive
  openiconic: list
#- text: some page
#  url: /anotherpage.html
#  openiconic: list-rich
- text: an About page
  url: /about.html
  openiconic: info
  
# Enter an invitation message
#    | It lies right beneath every post to invite your readers to react and comment
#    | {optional}
invitationmsg: If you have any feedback you would like me to read, please don't hesitate to send them over to <a href=mailto:you@domain.xyz>you@domain.xyz</a>.
